### PR TITLE
Add field's merge support

### PR DESCRIPTION
**Pull request by mikolamin**
Accordign to add merge field [PR](https://github.com/craftcms/cms/pull/15454). 
There’s a new MergeableFieldInterface, which field types must implement to opt into being mergeable.

### CODE REVIEW

**Comment by engram-design** [comment]
I've not looked into this yet, but is this a completed solution and tested? I was under the impression that we'd need to provide migration handling as per Brandon's write-up?

**Comment by mikolamin** [comment]
In my case migration was successful with this changes, but during it I turned off comparing the field settings in the fields/merge script due to the fact that Hyper fields always have differern setting in the config file.

**Comment by engram-design** [comment]
Gotcha, I'll be looking into that as well as the same time as I tackle this. We're planning on cleaning up the field settings a bit with the field layouts.

**Comment by mikolamin** [comment]
Thanks, looking forward to it!

**Comment by PhilReinking** [comment]
@engram-design Is there an update on when this will be merged?

**Comment by engram-design** [comment]
This is only a partial implementation, there's more work to be done to have it work fully.

**Comment by PhilReinking** [comment]
Anything I can do to help here?

For us, coming from Craft 4, we need to merge those Hyper fields to finish our migration to Craft 5.

**Comment by engram-design** [comment]
Added for the next release. To get this early, run `composer require verbb/hyper:"dev-craft-5 as 2.0.5"`.

**Pull request closed without merging**
