### PR TITLE
Add German translations

### PR DESCRIPTION
**Pull request by MoritzLost**
Ran the English translations through ChatGPT and reviewed them manually. Did pretty well except for a couple stylistic issues and some missing context stuff.

The labels for link types are not translatable, could you add those as translations? Those could also just utilize the core `app` translations. `Entry` should be `Eintrag` here, this translation already exists in the core (same for `Asset` -> `Datei` etc).

Screenshot 2024-05-22 at 18 11 33

### CODE REVIEW

**Comment by engram-design** [comment]
Thanks for this! I've actually just realised there are some missing strings (sorry about that) so you might want to check against the latest [translations](https://github.com/verbb/hyper/commit/5bf8b36e46f50d939e6bf2c2531d554b1b9ccd3b) to make any changes.

The tricky thing with link type labels is that they're user-defined, so they aren't translated automatically, just like other sorts of content is. This makes it tricky to swap out the "Entry" label with the `app` translations, and other with `hyper`. They're all now in the `hyper` file, so annoyingly a little bit of double-up.

For new Hyper fields, this label will be translated for the native elements, so that at least makes things easier. It's just that once the field is saved, and the label for the link type populated, we don't want that touched.

**Comment by MoritzLost** [comment]
@engram-design I've just rebased the branch and added all new translations!

> The tricky thing with link type labels is that they're user-defined, so they aren't translated automatically, just like other sorts of content is. This makes it tricky to swap out the "Entry" label with the app translations, and other with hyper. They're all now in the hyper file, so annoyingly a little bit of double-up.

Ah makes sense, I forgot about that.

> For new Hyper fields, this label will be translated for the native elements, so that at least makes things easier. It's just that once the field is saved, and the label for the link type populated, we don't want that touched.

Shouldn't the saved labels be translated when the field is displayed in the backend? That's what Craft fields do …

**Comment by engram-design** [comment]
Thanks once again for that, looks great.

> Shouldn't the saved labels be translated when the field is displayed in the backend? That's what Craft fields do …

I understand it does that for Craft, but I figure that's going to misleading. To illustrate what would happen. Let's say I create the Link Types in English, but view the control panel for this particular user in German. Showing the translated labels means there's a disconnect between what the value is, and what it's shown. 

What I _think_ you're suggesting is this would be shown:

CleanShot 2024-05-25 at 22 31 29@2x

I can't really translate the actual text in the input, as that's what it saves as, and it'll change depending on the editing users language.

When it comes to _displaying_ the link type, it's correctly translated depending on the `hyper` translation category for the users chosen control panel language.

CleanShot 2024-05-25 at 22 32 50@2x

**Comment by MoritzLost** [comment]
@engram-design Thanks for the explanation, and for merging the PR! Makes sense for Hyper to use the translated labels directly. I was a bit put off because applying the translations to new fields means the field settings depend on the current language of the user creating the field. But all those labels can be changed, so as a default it makes sense. In the end it's no difference from other custom field labels – if we write those in German, they won't pick up translations in other language. Not that common anyway to need a multilingual backend 👍

**Pull request merged**
